### ISSUE TITLE
Sometime Issue not initialise database file

### ISSUE THREAD

**Issue by ZalavadiaNirav** [jwhitehorn/SKDatabase#2]
HI 

I am big fan of skdatabase but currently I am facing issue that database file not initialise properly it return null.so nothing works.I am using Xcode 8.2.1 with ios10.

It's really weird issue in some project it works but In some project it won't be.

Hope you resolve quickly.

Thanks
Nirav

**Comment by jwhitehorn** [comment]
Hello,

Sorry to hear you're having problems. SKDatabase isn't something I work on any longer - not since 2012 actually. So, I really cannot be of much assistance with resolving this issue.

I'd recommend looking into [FMDB](https://github.com/ccgus/fmdb) as a good replacement that I know works under modern versions of Xcode and iOS.

**Comment by ZalavadiaNirav** [comment]
Hello

Thanks dear sometime I use fmdb but I really like skdatabase for small need.

Thanks
